# Generated by Django 4.1.7 on 2023-02-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ukr', models.CharField(max_length=20)),
                ('surname_ukr', models.CharField(max_length=30)),
                ('patronymic_ukr', models.CharField(max_length=20)),
                ('name_en', models.CharField(max_length=20)),
                ('surname_en', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=9)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('telegram_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=9)),
            ],
        ),
    ]
